accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import register

app_name = "accounts"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    # Passwords
    # change password urls
    path('password_change/',
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    # reset password urls
    path('password_reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

articles/urls.py
from django.urls import path, re_path
from .views import article_list, article_detail
app_name = 'articles'

urlpatterns = [
    path('', article_list, name='article_list'),
    re_path(r'(?P<slug>[-\w]+)/', article_detail, name='article_detail'),

]

gallery/urls.py
from django.urls import path, re_path
from .views import gallery_list, gallery_detail

app_name = 'gallery'

urlpatterns = [
    path('', gallery_list, name='gallery_list'),
    re_path(r'(?P<slug>[-\w]+)/', gallery_detail, name='gallery_detail'),
]

home/urls.py
from django.urls import path, re_path
from .views import news_list, news_detail, calculate_bmi, contact_us

app_name = 'news'

urlpatterns = [
    path('', news_list, name='news_list'),
    re_path(r'(?P<slug>[-\w]+)/جزییات/', news_detail, name='news_detail'),
    path('bmi', calculate_bmi, name='calculate_bmi'),
    path('contact-us', contact_us, name='contact_us')
]

order/urls.py
from django.urls import path

from order.views import add_user_order, user_open_order, remove_order_detail

app_name = 'order'
urlpatterns = [
    path('add-user-order', add_user_order, name='add_user_order'),
    path('سبد-خرید', user_open_order, name='user_open_order'),
    path('remove-order-detail/<detail_id>', remove_order_detail),
]

sport_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls', namespace='news')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls', namespace='articles')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('products/', include('products.urls', namespace='products')),
    path('gallery/', include('gallery.urls', namespace='gallery')),
    path('orders/', include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
                  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
                  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.urls import reverse


class NewsManager(models.Manager):
    def get_active_news(self) -> list:
        qs = News.objects.filter(is_active=True)
        return qs


class News(models.Model):
    title = models.CharField(max_length=250, verbose_name='عنوان')
    slug = models.SlugField(unique=True, allow_unicode=True, verbose_name='اسلاگ')
    image = models.ImageField(
        upload_to='news/images/', verbose_name='تصویر')
    description = models.TextField(verbose_name='متن خبر')
    created = models.DateTimeField(
        auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(
        auto_now=True, verbose_name='تاریخ بروزرسانی')
    is_active = models.BooleanField(verbose_name='فعال/غیرفعال')
    source_link = models.URLField(blank=True, null=True, verbose_name='منبع')

    class Meta:
        verbose_name = "خبر"
        verbose_name_plural = "اخبار"
        ordering = ['title', ]

    objects = NewsManager()

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('news:news_detail', args=[self.slug])


class ContactUs(models.Model):
    title = models.CharField(max_length=20, verbose_name='عنوان')
    description = models.TextField(verbose_name='توضیحات')
    email = models.EmailField(verbose_name='آدرس الکترونیکی')
    phone_number = models.IntegerField(max_length=11)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'تماس با ما'
        verbose_name_plural = 'پیام های تماس با ما'

        ordering = ['-created']

    def __str__(self):
        return self.title

home/forms.py
from django import forms


class BMIForm(forms.Form):
    height = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={"class": "form-control text-center", "placeholder": "قد (سانتی متر )"}),
        label='')

    weight = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={"class": "form-control text-center", "placeholder": "وزن ( کیلوگرم )"}),
        label='')


class ContactUsForm(forms.Form):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control text-center", "placeholder": "موضوع"}
        ),
        label='موضوع'
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={"class": "form-control text-center", "placeholder": "پیام"}
        ),
        label=''
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={"class": "form-control text-center", "placeholder": "ایمیل"}
        ),
        label=''
    )
    phone_number = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={"class": "form-control text-center", "placeholder": "شماره تلفن همراه"}),
        label='')

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import News, ContactUs
from django.core.paginator import Paginator
from .forms import BMIForm, ContactUsForm


# Create your views here.


def news_list(request):
    news = News.objects.get_active_news()
    last_five_news = news[0:5]

    paginator = Paginator(news, 6)  # Show 8 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        "news": news,
        "last_news": last_five_news,
        "page_obj": page_obj
    }

    return render(request, 'news_list.html', context)


def news_detail(request, slug):
    single_news = get_object_or_404(News, slug=slug)
    context = {
        'single_news': single_news
    }

    return render(request, 'news_detail.html', context)


def bim_suggestion(bmi):
    """
    Get the bmi and suggest a Diet.
    """
    suggestion = {
        bmi < 18.5: """رژیم غذایی مناسب برای تیپ بدنی کمتر از ۱۸/۵، شامل ۵۵٪ کربوهیدرات، ۲۵٪ پروتئین و ۲۰٪ چربی است. 

غذاهای توصیه شده
اگر متعلق به این گروه هستید، مواد غذایی زیر را در رژیم غذایی خود بگنجانید:

گوشت و مرغ
سبزیجات
شیر و تخم مرغ
انواع دانه‌های روغنی و آجیل
غلات کامل
نان و ماکارونی""",
        all([bmi > 18.5, bmi < 24.9]): """رژیم غذایی مناسب برای تیپ بدنی ۱۸/۵ الی ۲۴ شامل ۴۰٪ کربوهیدرات، ۳۰٪ پروتئین و ۳۰٪ چربی است. 

غذاهای توصیه شده

اگر متعلق به این گروه هستید، مواد غذایی زیر را در رژیم غذایی خود بگنجانید:

روغن‌های سالم مانند روغن زیتون و ذرت
میوه و سبزیجات فراوان
غلات
گوشت و ماهی بدون چربی و سویا
غذاهای سرشار از سدیم و کلسیم""",
        all([bmi > 25, bmi < 29.9]): """افراد با تیپ بدنی ۲۵ تا ۲۹، باید مصرف کربوهیدرات‌ها به ویژه مواد غذایی مانند نان، ماکارونی، آبمیوه‌های صنعتی و غلات را محدودتر کنند و در هنگام مصرف چربی حساسیت بالایی به خرج دهند.

تاکید اصلی برای افراد دارای اندام گلابی شکل، تلاش برای عضله‌سازی و حفظ وزن ایده‌آل بدن است. بهترین راه برای انجام این کار، مصرف پروتئین‌های کم‌چرب، سبزیجات و چربی‌های سالم است""",
        bmi > 30: """غذاهایی که افراد با این تیپ بدنی باید بخورند:

 غذاهای حاوی فیبر، حبوبات و کربوهیدرات‌های ساده از مواردی هستند که باید در برنامه غذایی این افراد گنجانده شوند. این مواد غذایی سبب حفظ انرژی بدن در مدت زمان طولانی می‌شوند. همچنین مصرف جو، برنج قهوه‌ای، عدس، لوبیا و سیب زمینی به این افراد توصیه می‌شود.

غذاهایی که افراد با این تیپ بدنی باید از آن‌ها اجتناب کنند:

افراد این دسته باید در مورد انواع چربی که مصرف می کنند، هوشیار باشند و چربی‌های ناسالم یا حیوانی استفاده نکنند. همچنین مصرف پنیر، خامه، کره، روغن کانولا و دانه‌های روغنی و آجیل در این افراد باید محدودتر شود""",
    }

    return suggestion[True]


def calculate_bmi(request):
    if request.method == 'POST':
        form = BMIForm(request.POST or None)
        if form.is_valid():
            height_cm = form.cleaned_data['height']
            weight_kg = form.cleaned_data['weight']

            height_metric = height_cm * 0.01
            bmi = round((weight_kg / (height_metric * height_metric)), 2)
            values = 'بی ام آی شما عدد ' + str(bmi) + ' می باشد'
            suggestion = bim_suggestion(bmi=bmi)
            context = {
                'form': form,
                'answer': values,
                'suggestion': suggestion
            }

            return render(request, 'calculate_bmi.html', context)
    form = BMIForm()
    print(form)
    context = {
        'form': form,
        'answer': None
    }
    return render(request, 'calculate_bmi.html', context)


def contact_us(request):
    if request.method == 'POST':
        print(100000)
        form = ContactUsForm(request.POST or None)
        if form.is_valid():
            print(200000)
            title = form.cleaned_data['title']
            description = form.cleaned_data['description']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            ContactUs.objects.create(
                title=title,
                description=description,
                email=email,
                phone_number=phone_number)
            print(300000)
            return redirect('/')
    print(400000)
    form = ContactUsForm()
    context = {
        "form": form
    }
    return render(request, 'contact_us.html', context)

home/templates/calculate_bmi.html
{% extends 'base.html' %}

{% block title %}
    محاسبه BMI
{% endblock %}


{% block content %}
    <h1 class="text-center bg-secondary py-2 text-white mt-5">محاسبه توده بدنی</h1>
    <div class="container border border-warning my-5 rounded">
        <h5 class="text-center text-white text-right mt-3">شاخص توده بدنی روشی برای محاسبه میزان چربی های بدن یک فرد بر
            اساس
            وزن و قد وی می باشد. با اینکه بی ام آی یک روش اندازه گیری غیر مستقیم است، اما ثابت شده که در اکثر مردم شاخصی
            قابل قبول برای محاسبه اضافه وزن به حساب می آید</h5>
        <br>
        <p class="text-left text-white">
            زیر ۱۸.۵ باشد، شخص دچار کاهش وزن است*
        </p>
        <p class="text-left text-white">
            بین ۱۸.۵ و ۲۴.۹ باشد، شخص در بازه ی وزن سالم به سر می برد*
        </p>
        <p class="text-left text-white">
            بین ۲۵ و ۲۹.۹ باشد، شخص اضافه وزن دارد*
        </p>
        <p class="text-left text-white">
            بین ۳۰ و ۳۹.۹ باشد، شخص از چاقی مفرط رنج می برد*
        </p>
        <div class="my-5">
            <div class="row justify-content-center">
                <form action="" method="post" class="form-control w-50">
                    {% csrf_token %}
                    <p class="text-center font-weight-bold">قد (سانتی متر)</p>
                    {{ form.height }}
                    <br>
                    <p class="text-center font-weight-bold">وزن (کیلوگرم)</p>
                    {{ form.weight }}
                    <br>
                    <button type="submit" class="btn btn-block text-white btn neon-btn">محاسبه</button>
                </form>
            </div>
            {% if answer %}
                <div class="row justify-content-center mt-5">
                    <h4 class="text-warning text-center">{{ answer }}</h4>
                    <br>

                    <p class="text-warning m-2">{{ suggestion }}</p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

home/templates/contact_us.html
{% extends 'base.html' %}


{% block title %}
    تماس با ما
{% endblock %}

{% block content %}
    <h1 class="bg-secondary py-1 rounded text-white text-center my-5">تماس با ما</h1>
    <div class="container">
        <div class="row justify-content-center">
            <form method="post" class="form-control my-5 w-75">
                {% csrf_token %}
                <h6 class="bg-warning py-2  rounded font-weight-bold text-dark text-center">عنوان</h6>
                {{ form.title }}
                <br>
                <h6 class="bg-warning py-2  rounded font-weight-bold text-dark text-center">ایمیل</h6>
                {{ form.email }}
                <br>
                <h6 class="bg-warning py-2  rounded font-weight-bold text-dark text-center">شماره تلفن</h6>
                {{ form.phone_number }}
                <br>
                <h6 class="bg-warning py-2  rounded font-weight-bold text-dark text-center">پبام</h6>
                {{ form.description }}
                <br>
                <button type="submit" class="btn btn-block text-white btn neon-btn">ارسال</button>
            </form>
        </div>
    </div>

{% endblock %}

home/templates/news_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ single_news.title }}
{% endblock title %}


{% block content %}
    <div class="container">
        <div class="card my-5 news-header">
            <div class="card-body">
                <h5 class="card-title text-center font-weight-bold">{{ single_news.title }}</h5>
                <br>
                <img src="{{ single_news.image.url }}" alt="" class="img-fluid img-rounded img-responsive">
                <br><br>
                <p class="card-text">{{ single_news.description }}</p>
                {% if single_news.source_link %}
                    <a href="{{ single_news.source_link }}">منبع</a>
                {% endif %}
                <hr>
                <p>{{ single_news.created |date }}</p>
            </div>
        </div>
    </div>
{% endblock content %}

home/templates/news_list.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center bg-secondary py-2 text-white mt-5">اخبار ورزشی</h1>
    <section class="container">
        <div class="row my-5">
            <!-- SideBar -->
            <div class="col-sm-3">
                <div class="card">
                    <h4 class="text-center font-weight-bold">آخرین خبر ها</h4>
                    <hr>
                    {% for last_new in last_news %}
                        <a href="{{ last_new.get_absolute_url }}">
                            <p class="text-center">{{ last_new.title }}</p>
                        </a>
                    {% endfor %}
                </div>
                <br>
                <div class="card">
                    <h4 class="text-center font-weight-bold">دیگر بخش ها</h4>
                    <hr>
                    <a class="text-dark text-center my-2" href="{% url "products:product_list" %}">فروشگاه</a>
                    <a class="text-dark text-center my-2" href="{% url "articles:article_list" %}">مقالات</a>
                    <a class="text-dark text-center my-2" href="{% url "notifications:notification_list" %}">اعلانات</a>
                    <a class="text-dark text-center my-2" href="{% url "gallery:gallery_list" %}">گالری تصاویر</a>
                    {% if user.is_authenticated %}
                        <a class="text-dark text-center my-2" href="{% url "order:user_open_order" %}">سبد خرید</a>
                        <a class="text-dark text-center my-2" href="{% url "accounts:logout" %}">خروج</a>
                    {% else %}
                        <a href="/accounts/register" class="text-dark text-center my-2">ثبت نام</a>
                        <a href="/accounts/login" class="text-dark text-center my-2">ورود</a>
                    {% endif %}
                </div>
            </div>
            <!-- News -->
            <div class="col-sm-9">
                <div class="row">
                    {% for single_news in page_obj %}
                        <div class="col-sm-4 mt-3">
                            <div class="card news-header news-card">
                                <div class="card-body ">
                                    <a href="{{ single_news.get_absolute_url }}" class="text-success">
                                        <p class="">{{ single_news.title | truncatechars:35 }}</p>
                                    </a>
                                    <img src="{{ single_news.image.url }}" alt="" class="img-responsive img-fluid">
                                    <p>{{ single_news.created |date }}</p>
                                    <p>{{ single_news.description | truncatechars:100 }}</p>
                                </div>

                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!-- Pagination -->
                <div class="pagination row justify-content-center my-5">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a class="p-1 rounded neon-btn" href="?page=1">&laquo; first</a>
                            <a class="p-1 rounded neon-btn"
                               href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current text-warning">
                            صفحه {{ page_obj.number }} از {{ page_obj.paginator.num_pages }}
                        </span>

                        {% if page_obj.has_next %}
                            <a class="neon-btn p-1 rounded" href="?page={{ page_obj.next_page_number }}">next</a>
                            <a class="p-1 rounded neon-btn"
                               href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </section>
{% endblock %}