articles/urls.py
from django.urls import path, re_path
from .views import article_list, article_detail
app_name = 'articles'

urlpatterns = [
    path('', article_list, name='article_list'),
    re_path(r'(?P<slug>[-\w]+)/', article_detail, name='article_detail'),

]

gallery/urls.py
from django.urls import path, re_path
from .views import gallery_list, gallery_detail

app_name = 'gallery'

urlpatterns = [
    path('', gallery_list, name='gallery_list'),
    re_path(r'(?P<slug>[-\w]+)/', gallery_detail, name='gallery_detail'),
]

home/urls.py
from django.urls import path, re_path
from .views import news_list, news_detail, calculate_bmi, contact_us

app_name = 'news'

urlpatterns = [
    path('', news_list, name='news_list'),
    re_path(r'(?P<slug>[-\w]+)/جزییات/', news_detail, name='news_detail'),
    path('bmi', calculate_bmi, name='calculate_bmi'),
    path('contact-us', contact_us, name='contact_us')
]

order/urls.py
from django.urls import path

from order.views import add_user_order, user_open_order, remove_order_detail

app_name = 'order'
urlpatterns = [
    path('add-user-order', add_user_order, name='add_user_order'),
    path('سبد-خرید', user_open_order, name='user_open_order'),
    path('remove-order-detail/<detail_id>', remove_order_detail),
]

products/urls.py
from django.urls import path, re_path
from .views import product_list, product_detail,product_category

app_name = 'products'

urlpatterns = [
    path('', product_list, name='product_list'),

    re_path(r'(?P<slug>[-\w]+)/detail/', product_detail, name='product_detail'),

    path('<int:pk>/دسته-بندی-ها/', product_category, name='product_category'),

]

sport_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls', namespace='news')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls', namespace='articles')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('products/', include('products.urls', namespace='products')),
    path('gallery/', include('gallery.urls', namespace='gallery')),
    path('orders/', include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
                  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
                  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert {{ message.tags }} alert-dismissible text-center font-weight-bold" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
                </button>

            {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/partials/footer.html
<!-- footer -->

<footer class="footer" id="footer">
    <div class="container">
        <div class="div d-flex justify-content-around py-3">
            <a href="https://www.telegram.com/"> <span class="footer-icon" target="_blank"><i
                    class="fab fa-telegram"></i></span></a>
            <a href="https://www.instagram.com/" target="_blank"> <span
                    class="footer-icon"><i class="fab fa-instagram"></i></span></a>
            <a href="https://www.linkedin.com/" target="_blank">
                <span class="footer-icon"><i class="fab fa-linkedin"></i></span></a>
        </div>
    </div>
</footer>

templates/partials/header.html
<!-- Head -->
<section class="hd" id="head">
    <section class="head">
        <div class="container">
            <div class="row my-5">
                <div class="col-12">
                    <!-- Alerts -->
                    {% include 'partials/_alerts.html' %}
                </div>
            </div>
        </div>
    </section>
</section>

templates/partials/navbar.html
<!-- nav -->
<section class="nav-section">
    <nav class="nav navbar-expand-lg justify-content-between">
        <div class="nav-brand d-flex px-1">
            {% if user.is_authenticated %}
                <h5 class="text-white font-weight-bold">خوش آمدید {{ request.user.first_name }} </h5>
            {% endif %}
        </div>

        <button class="navbar-toggler" data-target="#myNav" data-toggle="collapse" type="button">
                <span class="navbar-icon">
                    <i class="fas fa-bars"></i>
                </span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="myNav">
            <ul class="navbar-nav  align-items-center">
                <li class="navbar-item px-2"><a href="/" class="nav-link text-capitalize nav-items">خانه</a></li>

                <li class="navbar-item px-2"><a href="{% url 'news:contact_us' %}"
                                                class="nav-link text-capitalize nav-items">تماس با ما
                </a>
                </li>


                <li class="navbar-item px-2"><a href="{% url 'articles:article_list' %}"
                                                class="nav-link text-capitalize nav-items">مقالات
                </a>
                </li>

                <li class="navbar-item px-2"><a href="{% url 'notifications:notification_list' %}"
                                                class="nav-link text-capitalize nav-items">اعلانات
                </a>
                </li>

                <li class="navbar-item px-2"><a href="{% url 'news:calculate_bmi' %}"
                                                class="nav-link text-capitalize nav-items">شاخص توده بدنی
                </a>
                </li>

                <li class="navbar-item px-2"><a href="{% url 'products:product_list' %}"
                                                class="nav-link text-capitalize nav-items">فروشگاه
                </a>
                </li>

                <li class="navbar-item px-2">
                    <a href="{% url 'gallery:gallery_list' %}"
                       class="nav-link text-capitalize nav-items">گالری تصاویر
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="navbar-item px-2">
                        <a href="{% url 'order:user_open_order' %}"
                           class=" nav-link text-capitalize nav-items">سبد خرید
                        </a>
                    </li>
                    <li class="navbar-item px-2">
                        <a href="/accounts/logout"
                           class="nav-link text-capitalize nav-items">خروج
                        </a>
                    </li>
                {% else %}
                    <li class="navbar-item px-2">
                        <a href="/accounts/register"
                           class="nav-link text-capitalize nav-items">ثبت نام
                        </a>
                    </li>
                    <li class="navbar-item px-2">
                        <a href="/accounts/login"
                           class="nav-link text-capitalize nav-items">ورود
                        </a>
                    </li>
                {% endif %}


            </ul>
        </div>
    </nav>
</section>