home/urls.py
from django.urls import path, re_path
from .views import news_list, news_detail, calculate_bmi, contact_us

app_name = 'news'

urlpatterns = [
    path('', news_list, name='news_list'),
    re_path(r'(?P<slug>[-\w]+)/جزییات/', news_detail, name='news_detail'),
    path('bmi', calculate_bmi, name='calculate_bmi'),
    path('contact-us', contact_us, name='contact_us')
]

order/urls.py
from django.urls import path

from order.views import add_user_order, user_open_order, remove_order_detail

app_name = 'order'
urlpatterns = [
    path('add-user-order', add_user_order, name='add_user_order'),
    path('سبد-خرید', user_open_order, name='user_open_order'),
    path('remove-order-detail/<detail_id>', remove_order_detail),
]

products/urls.py
from django.urls import path, re_path
from .views import product_list, product_detail,product_category

app_name = 'products'

urlpatterns = [
    path('', product_list, name='product_list'),

    re_path(r'(?P<slug>[-\w]+)/detail/', product_detail, name='product_detail'),

    path('<int:pk>/دسته-بندی-ها/', product_category, name='product_category'),

]

sport_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls', namespace='news')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls', namespace='articles')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('products/', include('products.urls', namespace='products')),
    path('gallery/', include('gallery.urls', namespace='gallery')),
    path('orders/', include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
                  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
                  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=200, verbose_name="عنوان")
    slug = models.SlugField(default="اسلاگ", allow_unicode=True, unique=True, verbose_name="اسلاگ")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"

    def get_absolute_url(self):
        return reverse('products:product_category', args=[self.id])


class ProductManager(models.Manager):
    def get_active_products(self):
        qs = Product.objects.filter(is_active=True)
        if qs:
            return qs


class Product(models.Model):
    category = models.ManyToManyField(
        Category, related_name="category", verbose_name="دسته بندی")
    title = models.CharField(max_length=250, verbose_name='عنوان محصول')
    slug = models.SlugField(unique=True, allow_unicode=True, verbose_name='اسلاگ')
    price = models.IntegerField(default=0.00, verbose_name="قیمت")
    description = models.TextField(verbose_name='توضیحات محصول')
    main_image = models.ImageField(
        upload_to=f'products/images/', verbose_name='عکس اصلی')
    created = models.DateTimeField(
        auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = models.DateTimeField(
        auto_now=True, verbose_name='تاریخ بروزرسانی')
    is_active = models.BooleanField(verbose_name='فعال/غیرفعال')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'
        ordering = ['title', ]

    def get_absolute_url(self):
        return reverse('products:product_detail', args=[self.slug])

    objects = ProductManager()


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(
        upload_to=f'products/images/', verbose_name='تصویر')

    class Meta:
        verbose_name = "گالری تصاویر"
        verbose_name_plural = "گالری تصاویر"

products/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from order.forms import UserNewOrderFOrm
from .models import Product, Category, ProductImage


# Create your views here.


def product_list(request):
    products = Product.objects.get_active_products().order_by('-created')
    paginator = Paginator(products, 5)  # Show 8 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    categories = Category.objects.all()
    context = {
        "products": products,
        "categories": categories,
        'page_obj': page_obj
    }

    return render(request, 'products_list.html', context)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    new_order_form = UserNewOrderFOrm(request.POST or None, initial={'product_id': product.id})
    product_gallery = ProductImage.objects.filter(product=product)
    products = Product.objects.get_active_products()[0:6]
    context = {
        'product': product,
        "product_gallery": product_gallery,
        "products": products,
        'new_order_form': new_order_form
    }

    return render(request, 'products_detail.html', context)


def product_category(request, pk):
    category = Category.objects.filter(id=pk)
    categories = Category.objects.all()
    products = Product.objects.filter(category__in=category).order_by('-created')
    paginator = Paginator(products, 5)  # Show 8 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        "products": products,
        "categories": categories,
        "category_title": category,
        "page_obj": page_obj,
    }
    print(category)
    return render(request, 'products_list.html', context)

products/templates/products_detail.html
{% extends "base.html" %}
{% block title %}
    {{ product.title }}
{% endblock %}

{% block content %}
    <div class="container my-5">
        <div class="card p-2 mb-5">
            <div class="row">
                <div class="col-sm-7">
                    <h2 class="text-dark">{{ product.title }}</h2>
                    <hr>
                    <p class="text-dark">{{ product.description }}</p>
                    <form action="{% url 'order:add_user_order' %}" method="post">
                        {% csrf_token %}
                        {{ new_order_form.product_id }}

                        <div class="row justify-content-between">
                            <div class="col-3">
                                <p class="text-left">
                                    {{ new_order_form.count }}
                                </p>
                            </div>
                            <div class="col-6">
                                <p>قیمت: {{ product.price }} ریال</p>
                            </div>

                        </div>
                        <button type="submit" class="text-white btn neon-btn btn-block">افزودن به سبد خرید</button>
                    </form>
                    <p class="text-secondary mt-3" style="font-size: 12px">{{ product.created |date }}</p>
                </div>
                <!-- Images -->
                <div class="col-sm-5">
                    <a href="{{ product.main_image.url }}" class="mb-1">
                        <img src="{{ product.main_image.url }}" alt="{{ product.title }}" class="img-fluid rounded">
                    </a>
                    <br>
                    <div class="row mt-1">
                        {% for pic in product_gallery %}
                            <div class="col-3">
                                <a href="{{ pic.image.url }}">
                                    <img src="{{ pic.image.url }}" alt="" class="img-fluid rounded">
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Other Products -->
        <h4 class="text-white bg-secondary py-2">محصولات دیگر</h4>
        <div class="row mt-5">
            {% for p in products %}
                <div class="col-sm-4 mt-2">
                    <div class="card">
                        <div class="card-header">
                            {{ p.title }}
                        </div>
                        <div class="card-body">
                            <a href="{{ p.get_absolute_url }}">
                                <img src="{{ p.main_image.url }}" class="img-fluid" alt="">
                            </a>
                        </div>
                        <div class="card-footer">
                            <p class="text-secondary">{{ p.created|date }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

products/templates/products_list.html
{% extends "base.html" %}


{% block title %}
    Products
{% endblock %}

{% block content %}
    <h1 class="text-center bg-secondary py-2 text-white mt-5">فروشگاه</h1>
    {% for foo in category_title %}
        <h2 class="text-center text-danger">دسته بندی {{ foo.title }}</h2>
    {% endfor %}

    <div class="container my-3">
        <div class="row">
            <!-- Categories -->
            <div class="col-sm-3 p-3">
                <aside>
                    <h4 class="text-center text-white">دسته بندی ها</h4>
                    <br>
                    <div class="card px-3">
                        <a href="/products/" class="py-1">
                                <h6 class="text-center text-danger">
                                    همه
                                </h6>
                            </a>
                            <hr>
                        {% for category in categories %}
                            <a href="{{ category.get_absolute_url }}" class="py-1">
                                <h6 class="text-center text-danger">
                                    {{ category.title }}
                                </h6>
                            </a>
                            <hr>
                        {% endfor %}
                    </div>
                </aside>
            </div>
            <!-- Products -->
            <div class="col-sm-9 p-3">
                <h4 class="text-center text-white">محصولات</h4>
                <hr>
                {% for product in page_obj %}
                    <div class="card my-3 p-1">
                        <div class="row">
                            <!-- Product Information -->
                            <div class="col-sm-8">
                                <h5 class="text-danger">{{ product.title }}</h5>
                                <hr>
                                <p>قیمت: {{ product.price }} ریال</p>
                                <p>{{ product.description |truncatewords:40 }}</p>
                                <a href="{{ product.get_absolute_url }}" class="text-white btn neon-btn">
                                    مشاهده جزییات
                                </a>

                            </div>
                            <!-- Product Main Image -->
                            <div class="col-sm-4">
                                <div>
                                    <img class="img-fluid rounded" src="{{ product.main_image.url }}" alt="">
                                </div>
                            </div>

                        </div>
                    </div>
                {% endfor %}
                <!-- Pagination -->
                <div class="pagination row justify-content-center">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a class="p-1 rounded neon-btn" href="?page=1">&laquo; first</a>
                            <a class="p-1 rounded neon-btn" href="?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current text-warning">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a class="neon-btn p-1 rounded" href="?page={{ page_obj.next_page_number }}">next</a>
                            <a class="p-1 rounded neon-btn" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}