accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import register

app_name = "accounts"
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    # Passwords
    # change password urls
    path('password_change/',
         auth_views.PasswordChangeView.as_view(),
         name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(),
         name='password_change_done'),

    # reset password urls
    path('password_reset/',
         auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

home/urls.py
from django.urls import path, re_path
from .views import news_list, news_detail, calculate_bmi, contact_us

app_name = 'news'

urlpatterns = [
    path('', news_list, name='news_list'),
    re_path(r'(?P<slug>[-\w]+)/جزییات/', news_detail, name='news_detail'),
    path('bmi', calculate_bmi, name='calculate_bmi'),
    path('contact-us', contact_us, name='contact_us')
]

sport_news/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls', namespace='news')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls', namespace='articles')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('products/', include('products.urls', namespace='products')),
    path('gallery/', include('gallery.urls', namespace='gallery')),
    path('orders/', include('order.urls', namespace='order')),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + \
                  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
                  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

home/forms.py
from django import forms


class BMIForm(forms.Form):
    height = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={"class": "form-control text-center", "placeholder": "قد (سانتی متر )"}),
        label='')

    weight = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={"class": "form-control text-center", "placeholder": "وزن ( کیلوگرم )"}),
        label='')


class ContactUsForm(forms.Form):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control text-center", "placeholder": "موضوع"}
        ),
        label='موضوع'
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={"class": "form-control text-center", "placeholder": "پیام"}
        ),
        label=''
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={"class": "form-control text-center", "placeholder": "ایمیل"}
        ),
        label=''
    )
    phone_number = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={"class": "form-control text-center", "placeholder": "شماره تلفن همراه"}),
        label='')

accounts/views.py
from django.shortcuts import render
from .forms import UserRegistrationForm


# Create your views here.

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST or None)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request,
                          'register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'register.html',
                  {'user_form': user_form})

accounts/templates/register.html
{% extends "base.html" %}
{% block title %}Create an account{% endblock %}
{% block content %}
    <div class="container">
        <h1 class="text-center text-white mt-5 bg-warning p-1 rounded">ثبت نام</h1>
        <p class="text-center text-white">لطفا توسط فرم زیر ثبت نام کنید</p>
        <div class="row justify-content-center text-center">
            <div class="my-5">
                <form method="post" class="form-control">

                    <!-- Username -->
                    <label for="id_username" class="my-3 font-weight-bold" style="font-size: 25px;">نام کاربری</label>
                    <input class="form-control text-center" type="text" name="username" maxlength="150" required=""
                           id="id_username">
                    <p class="" style="font-size: 12px;">الزامی. 150 کاراکتر یا کمتر. فقط شامل حروف، اعداد، و علامات
                        @/./+/-/_</p>
                    </p>
                    <!-- Name -->
                    <label for="id_first_name" class="my-3 font-weight-bold">نام</label>
                    <input class="form-control text-center" type="text" name="first_name" maxlength="150"
                           id="id_first_name">

                    <!-- Family -->
                    <label for="id_last_name" class="my-3 font-weight-bold">نام خانوادگی</label>
                    <input class="form-control text-center" type="text" name="last_name" maxlength="150"
                           id="id_last_name">

                    <!-- Email -->
                    <label for="id_email" class="my-3 font-weight-bold">آدرس ایمیل</label>
                    <input class="form-control text-center" type="email" name="email" maxlength="254" id="id_email">

                    <!-- Password -->
                    <label for="id_password" class="my-3 font-weight-bold">رمز عبور</label>
                    <input class="form-control text-center" type="password" name="password" required=""
                           id="id_password">
                    <!-- Password2 -->
                    <label for="id_password2" class="my-3 font-weight-bold">تکرار رمز عبور</label>
                    <input class="form-control text-center" type="password" name="password2" required="" id="id_password2">
                    <input type="hidden" name="csrfmiddlewaretoken"
                           value="k5oZNSRA7dtRAQh3PXKyYsnyb2DH816MDyJglE7eR7GiniBi0QKqgKb3xu3ahXKY">

                    <input type="submit" class="my-3 btn btn-warning btn-block font-weight-bold" value="ثبت نام">
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/register_done.html
{% extends "base.html" %}
{% block title %}Welcome{% endblock %}
{% block content %}
    <div class="container my-5">
        <h1 class="text-center text-warning">Welcome {{ new_user.first_name }}!</h1>
        <p  class="text-center text-warning">Your account has been successfully created. Now you can
            <a class="text-danger" href="{% url "accounts:login" %}">log in</a>.</p>
    </div>
{% endblock %}